name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.3'
          channel: stable
          cache: true

      - name: Enable Flutter web
        run: flutter config --enable-web

      - name: Preheat Flutter
        run: flutter --version

      - name: Ensure web scaffolding (if missing)
        working-directory: pomodoro_super_app
        run: |
          if [ ! -f web/index.html ]; then
            flutter create .
          fi

      - name: Get dependencies
        working-directory: pomodoro_super_app
        run: flutter pub get

      - name: Build web
        working-directory: pomodoro_super_app
        run: flutter build web --release --base-href /Form/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: pomodoro_super_app/build/web
          publish_branch: gh-pages
          force_orphan: true
