name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'  # Użyj konkretnej wersji Fluttera (sprawdź, która pasuje do Twojego projektu)
          channel: 'stable'
          cache: true  # Przyspiesza budowanie przez cache'owanie zależności

      - name: Get dependencies
        run: flutter pub get

      - name: Build web app
        run: flutter build web --release --base-href /Responsive-Blog-Theme-using-Flutter/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          keep_files: false
          force_orphan: true
